// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DomReady(arg1) {
  return window['go']['app']['App']['DomReady'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function InviteSocket(arg1, arg2) {
  return window['go']['app']['App']['InviteSocket'](arg1, arg2);
}

export function NotifyBackend(arg1) {
  return window['go']['app']['App']['NotifyBackend'](arg1);
}

export function SendMsgToBackend(arg1) {
  return window['go']['app']['App']['SendMsgToBackend'](arg1);
}
