// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<void>;

export function InviteSocket(arg1:string,arg2:number):Promise<boolean>;
